notifications:
  webhooks:
    - https://webhook.commit-email.info/

env:
  global:
    - CC_TEST_REPORTER_ID=7e9fdb9b0066c819e6f0554e4ac81255f4f01d8da2a42ac1152402797e927401
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  include:
    - name: "master"
      rvm: ruby-head
