name: Test

on:
  - push
  - pull_request

jobs:
  in-place:
    name: "In-place test: Ruby ${{ matrix.ruby-version }}: ${{ matrix.runs-on }}"
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.5
          - 2.6
          - 2.7
        runs-on:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          bundle install
      - name: Test
        run: |
          bundle exec rake

  scanner:
    name: "Scanner test: Ruby ${{ matrix.ruby-version }}: ${{ matrix.runs-on }}"
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.7
        runs-on:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    env:
      CSV_PARSER_SCANNER_TEST: "yes"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          bundle install
      - name: Test
        run: |
          bundle exec rake

  gem:
    name: "Gem test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Install
        run: |
          rake install
          gem install simplecov
      - name: Test
        run: |
          mkdir -p tmp
          cd tmp
          cp -a ../test/ ./
          ../run-test.rb

  document:
    name: "Document test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Install dependencies
        run: |
          bundle install
      - name: Build document
        run: |
          bundle exec rake warning:error rdoc
      - name: Deploy
        if: |
          github.event_name == 'push'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          rm html/created.rid
          touch html/.nojekyll
          mv html ../
          rsync \
            -a \
            --delete \
            --exclude "/.git/" \
            ../html/ \
            ./
          if [ "$(git status --porcelain)" != "" ]; then
            git add --all
            git commit -m "Generate (${GITHUB_SHA})"
            git push
          fi
